image: python:3.10

stages:
  - test

unit_tests:
  stage: test
  only:
    - Release
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
    - echo "pytest..."
    - pytest tests/
